# 指定激活的环境（dev / prod）
spring:
  profiles:
    active: prod
  application:
    name: steamed-dish-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.128:8848   # Nacos 地址
      config:
        server-addr: 192.168.100.128:8848
        namespace: ${spring.profiles.active:public}